import { CommonLayout } from '@repo/ui/components/ui/commomLayout';
import AutoGeneratedMentoringForm from '../../../../../components/pages/main/mentor/auto-generated/AutoGeneratedMetoringForm';

export default function page() {
  return (
    <CommonLayout className="p-6">
      <h1 className="font-bold text-3xl py-3">멘토링 일괄생성</h1>
      <AutoGeneratedMentoringForm />
    </CommonLayout>
  );
}
