'use client';

import '@repo/ui/components/Select/select';
import { Input } from '@repo/ui/components/ui/input';
import { FormValues } from './AutoGeneratedMetoringForm';

type AutoMentoringFieldProps = {
  formValues: FormValues;
  setFormValues: (e: React.ChangeEvent<HTMLInputElement>) => void;
};

export default function AutoMentoringField({
  formValues,
  setFormValues,
}: AutoMentoringFieldProps) {
  const today = new Date();
  const formattedToday = today.toISOString().split('T')[0];

  const ninetyDaysLater = new Date(today);
  ninetyDaysLater.setDate(today.getDate() + 90);
  const formattedNinetyDaysLater = ninetyDaysLater.toISOString().split('T')[0];
  return (
    <section className="container py-4 my-8">
      <div className="grid grid-cols-2 gap-4">
        <div className="space-y-2">
          <label htmlFor="minParticipants">최소 참가자 수</label>
          <Input
            id="minParticipants"
            type="number"
            value={formValues?.minParticipants}
            name="minParticipants"
            onChange={setFormValues}
            required
          />
        </div>
        <div className="space-y-2">
          <label htmlFor="maxParticipants">최대 참가자 수</label>
          <Input
            id="maxParticipants"
            type="number"
            value={formValues?.maxParticipants}
            name="maxParticipants"
            onChange={setFormValues}
            required
          />
        </div>
        <div className="space-y-2">
          <label htmlFor="price">가격 (Volt)</label>
          <Input
            id="price"
            type="number"
            value={formValues?.price}
            name="price"
            onChange={setFormValues}
            required
          />
        </div>
        <div className="space-y-2">
          <label htmlFor="deadline">자동생성 마감일</label>
          <Input
            id="deadline"
            type="date"
            value={formValues?.deadline}
            name="deadline"
            onChange={setFormValues}
            required
            style={{ fontSize: '1rem' }}
            min={formattedToday}
            max={formattedNinetyDaysLater}
          />
        </div>
      </div>
    </section>
  );
}
