import { Card, CardContent, CardHeader } from '@repo/ui/components/ui/card';
import { TimeSlot } from './AutoGeneratedMetoringForm';
import SelectedTime from './SelectedTime';

// SelectedTimes 컴포넌트
type SelectedTimesProps = {
  schedule: Record<string, TimeSlot[]>;
  removeTimeSlot: (day: string, index: number) => void;
};

export default function SelectedTimes({
  schedule = {},
  removeTimeSlot,
}: SelectedTimesProps) {
  const DAYS_OF_WEEK = Object.keys(schedule);

  return (
    <Card className="w-full lg:w-1/2">
      <CardHeader>
        <h1>선택된 시간</h1>
      </CardHeader>
      <CardContent>
        <div className="pr-4">
          {DAYS_OF_WEEK.map(
            (day) =>
              schedule[day]?.length > 0 && (
                <div key={day} className="mb-4">
                  <h3 className="font-semibold mb-2">{day}</h3>
                  <ul className="space-y-2">
                    {schedule[day].map((slot, index) => (
                      <SelectedTime
                        key={`${day}-${index}`}
                        day={day}
                        index={index}
                        start={slot.start}
                        end={slot.end}
                        removeTimeSlot={removeTimeSlot}
                      />
                    ))}
                  </ul>
                </div>
              )
          )}
        </div>
      </CardContent>
    </Card>
  );
}
